# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(654, 471)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 654, 23))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuaction = QtWidgets.QMenu(self.menubar)
        self.menuaction.setObjectName("menuaction")
        self.menulayer = QtWidgets.QMenu(self.menubar)
        self.menulayer.setObjectName("menulayer")
        self.menuvector = QtWidgets.QMenu(self.menulayer)
        self.menuvector.setObjectName("menuvector")
        self.menuraster = QtWidgets.QMenu(self.menulayer)
        self.menuraster.setObjectName("menuraster")
        self.menumaptool = QtWidgets.QMenu(self.menubar)
        self.menumaptool.setObjectName("menumaptool")
        self.menuhelp = QtWidgets.QMenu(self.menubar)
        self.menuhelp.setObjectName("menuhelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionZoomin = QtWidgets.QAction(MainWindow)
        self.actionZoomin.setObjectName("actionZoomin")
        self.actionZoomout = QtWidgets.QAction(MainWindow)
        self.actionZoomout.setObjectName("actionZoomout")
        self.actionIdentity = QtWidgets.QAction(MainWindow)
        self.actionIdentity.setObjectName("actionIdentity")
        self.actionShapefile = QtWidgets.QAction(MainWindow)
        self.actionShapefile.setObjectName("actionShapefile")
        self.actionCsv = QtWidgets.QAction(MainWindow)
        self.actionCsv.setObjectName("actionCsv")
        self.actionRectangle = QtWidgets.QAction(MainWindow)
        self.actionRectangle.setObjectName("actionRectangle")
        self.actionPolygon = QtWidgets.QAction(MainWindow)
        self.actionPolygon.setObjectName("actionPolygon")
        self.actionCircle = QtWidgets.QAction(MainWindow)
        self.actionCircle.setObjectName("actionCircle")
        self.actionPoint = QtWidgets.QAction(MainWindow)
        self.actionPoint.setObjectName("actionPoint")
        self.actionLine = QtWidgets.QAction(MainWindow)
        self.actionLine.setObjectName("actionLine")
        self.actionXYZ = QtWidgets.QAction(MainWindow)
        self.actionXYZ.setObjectName("actionXYZ")
        self.actionTransform = QtWidgets.QAction(MainWindow)
        self.actionTransform.setObjectName("actionTransform")
        self.actionPan = QtWidgets.QAction(MainWindow)
        self.actionPan.setObjectName("actionPan")
        self.actionAboutQt = QtWidgets.QAction(MainWindow)
        self.actionAboutQt.setObjectName("actionAboutQt")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menufile.addAction(self.actionOpen)
        self.menufile.addSeparator()
        self.menufile.addAction(self.actionQuit)
        self.menuaction.addAction(self.actionPan)
        self.menuaction.addAction(self.actionZoomin)
        self.menuaction.addAction(self.actionZoomout)
        self.menuaction.addAction(self.actionIdentity)
        self.menuvector.addAction(self.actionShapefile)
        self.menuvector.addAction(self.actionCsv)
        self.menuraster.addAction(self.actionXYZ)
        self.menulayer.addAction(self.menuvector.menuAction())
        self.menulayer.addAction(self.menuraster.menuAction())
        self.menumaptool.addAction(self.actionPoint)
        self.menumaptool.addAction(self.actionLine)
        self.menumaptool.addAction(self.actionPolygon)
        self.menumaptool.addAction(self.actionRectangle)
        self.menumaptool.addAction(self.actionCircle)
        self.menuhelp.addAction(self.actionAboutQt)
        self.menuhelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuaction.menuAction())
        self.menubar.addAction(self.menulayer.menuAction())
        self.menubar.addAction(self.menumaptool.menuAction())
        self.menubar.addAction(self.menuhelp.menuAction())

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        MainWindow.setWindowTitle("Főablak")
        self.menufile.setTitle("Projekt")
        self.menuaction.setTitle("Akció")
        self.menulayer.setTitle("Réteg")
        self.menuvector.setTitle("Vektor")
        self.menuraster.setTitle("Raszter")
        self.menumaptool.setTitle("Segédletek")
        self.menuhelp.setTitle("Súgó")
        self.dockWidget.setWindowTitle("Rétegek")
        self.actionOpen.setText("Betölt")
        self.actionQuit.setText("Kilépés")
        self.actionZoomin.setText("Nagyít")
        self.actionZoomout.setText("Kicsinyít")
        self.actionIdentity.setText("Adatlap")
        self.actionShapefile.setText("Shapefile")
        self.actionCsv.setText("CSV")
        self.actionRectangle.setText("Rectangle")
        self.actionPolygon.setText("Polygon")
        self.actionCircle.setText("Circle")
        self.actionPoint.setText("Point")
        self.actionLine.setText("Line")
        self.actionXYZ.setText("XYZ")
        self.actionPan.setText("Pan")
        self.actionAboutQt.setText("Qt névjegye")
        self.actionAbout.setText("Névjegy")

